# Generated by Django 5.2.5 on 2025-08-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='flight',
            field=models.ManyToManyField(blank=True, related_name='passengers', to='flight.flight'),
        ),
    ]
